services:

  ts-nginx:
    image: tailscale/tailscale:latest
    container_name: ts-nginx
    hostname: nginx
    environment:
      - TS_AUTHKEY=tskey-client-?ephemeral=false
      - "TS_EXTRA_ARGS=--advertise-tags=tag:container --reset"
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ts-nginx:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  nginx:
      image: nginx
      container_name: nginx
      network_mode: service:ts-nginx
      depends_on:
        - ts-nginx
volumes:
  ts-nginx:
    driver: local
  nginx:
    driver: local
